// <auto-generated />
using System;
using Foxus.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Foxus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FoxusDbContext))]
    [Migration("20220919224042_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Foxus.Domain.Execucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time")
                        .HasColumnName("DURACAO");

                    b.Property<int?>("PomodoroTimerId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PomodoroTimerId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EXECUCAO");
                });

            modelBuilder.Entity("Foxus.Domain.PomodoroTimer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("TempoDescanso")
                        .HasColumnType("time")
                        .HasColumnName("TEMPODESCANSO");

                    b.Property<TimeSpan>("TempoFoco")
                        .HasColumnType("time")
                        .HasColumnName("TEMPOFOCO");

                    b.HasKey("Id");

                    b.ToTable("POMODOROTIMER");
                });

            modelBuilder.Entity("Foxus.Domain.TarefaPrimaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("DATACADASTRO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time")
                        .HasColumnName("DURACAO");

                    b.Property<int?>("ExecucaoId")
                        .HasColumnType("int");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit")
                        .HasColumnName("FINALIZADA");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("PRIORIDADE");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("ExecucaoId");

                    b.ToTable("TAREFAPRIMARIA");
                });

            modelBuilder.Entity("Foxus.Domain.TarefaSecundaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit")
                        .HasColumnName("FINALIZADA");

                    b.Property<int?>("TarefaPrimariaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("TarefaPrimariaId");

                    b.ToTable("TAREFASECUNDARIA");
                });

            modelBuilder.Entity("Foxus.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("Foxus.Domain.Execucao", b =>
                {
                    b.HasOne("Foxus.Domain.PomodoroTimer", "PomodoroTimer")
                        .WithMany()
                        .HasForeignKey("PomodoroTimerId");

                    b.HasOne("Foxus.Domain.Usuario", "Usuario")
                        .WithMany("Execucoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PomodoroTimer");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Foxus.Domain.TarefaPrimaria", b =>
                {
                    b.HasOne("Foxus.Domain.Execucao", null)
                        .WithMany("TarefasPrimarias")
                        .HasForeignKey("ExecucaoId");
                });

            modelBuilder.Entity("Foxus.Domain.TarefaSecundaria", b =>
                {
                    b.HasOne("Foxus.Domain.TarefaPrimaria", null)
                        .WithMany("TarefasSecundarias")
                        .HasForeignKey("TarefaPrimariaId");
                });

            modelBuilder.Entity("Foxus.Domain.Execucao", b =>
                {
                    b.Navigation("TarefasPrimarias");
                });

            modelBuilder.Entity("Foxus.Domain.TarefaPrimaria", b =>
                {
                    b.Navigation("TarefasSecundarias");
                });

            modelBuilder.Entity("Foxus.Domain.Usuario", b =>
                {
                    b.Navigation("Execucoes");
                });
#pragma warning restore 612, 618
        }
    }
}
